### ISSUE TITLE
Поддержка библиотеки

### ISSUE THREAD

**Issue by amr-dallin** [artpol/photolabel#1]
Здравствуйте. Спасибо за вашу работу. Прекрасная библиотека. Вопрос один - проводится развитие  и поддержка проекта?

**Comment by artpol** [comment]
Добрый день!

К сожалению, уже давно не поддерживаю этот плагин.

**Comment by amr-dallin** [comment]
Очень жаль. Можете посоветовать альтернативные, поддерживаемые проекты?

Спасибо.

**Comment by artpol** [comment]
К сожалению, абсолютно не в курсе, как обстоят дела с аналогичными плагинами в настоящее время.
